import type { ResourceConfig } from './types'
import { P, TENANT } from './types'

export const resourceConfig: ResourceConfig = {
	label: 'Alert',
	description: 'Manage alerts, security incidents, audit logs, and webhook alerts',
	operations: {
		getAll: {
			method: 'GET',
			endpoint: '/api/ListAlertsQueue',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {},
			description: 'List all queued alerts',
		},
		add: {
			method: 'POST',
			endpoint: '/api/AddAlert',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				alertConfig: P.bodyJson('Alert configuration JSON', true),
			},
			description: 'Add alert configuration',
		},
		getSecurityAlerts: {
			method: 'GET',
			endpoint: '/api/ExecAlertsList',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List security alerts',
		},
		getSecurityIncidents: {
			method: 'GET',
			endpoint: '/api/ExecIncidentsList',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List security incidents',
		},
		setSecurityAlertStatus: {
			method: 'POST',
			endpoint: '/api/ExecSetSecurityAlert',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				GUID: P.body('Alert GUID', true),
				Status: P.body('New status', true),
			},
			description: 'Set security alert status',
		},
		setSecurityIncidentStatus: {
			method: 'POST',
			endpoint: '/api/ExecSetSecurityIncident',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				GUID: P.body('Incident GUID', true),
				Status: P.body('New status', true),
				Assigned: P.body('Assigned to user'),
			},
			description: 'Set incident status',
		},
		searchAuditLog: {
			method: 'POST',
			endpoint: '/api/ExecAuditLogSearch',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {},
			description: 'Search audit logs',
		},
		listAuditLogSearches: {
			method: 'GET',
			endpoint: '/api/ListAuditLogSearches',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				SearchId: P.qs('Filter by search ID'),
			},
			description: 'List audit log searches',
		},
		testAuditLog: {
			method: 'GET',
			endpoint: '/api/ListAuditLogTest',
			isWrite: false,
			isList: false,
			tenant: TENANT.qs,
			params: {
				SearchId: P.qs('Search ID to test'),
			},
			description: 'Test audit log',
		},
		listWebhookAlerts: {
			method: 'GET',
			endpoint: '/api/ListWebhookAlert',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {},
			description: 'List webhook alerts',
		},
		removeQueuedAlert: {
			method: 'POST',
			endpoint: '/api/RemoveQueuedAlert',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Alert queue ID'),
				EventType: P.body('Event type filter'),
			},
			description: 'Remove queued alert',
		},
		listMdoAlerts: {
			method: 'GET',
			endpoint: '/api/ExecMdoAlertsList',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List MDO alerts',
		},
		setMdoAlert: {
			method: 'POST',
			endpoint: '/api/ExecSetMdoAlert',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				GUID: P.body('MDO alert GUID', true),
			},
			description: 'Set MDO alert',
		},
		addAlertRule: {
			method: 'POST',
			endpoint: '/api/ExecAddAlert',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				text: P.body('Alert text'),
				Severity: P.body('Severity level'),
				email: P.body('Email recipient'),
				webhook: P.body('Webhook URL'),
			},
			description: 'Add alert rule',
		},
	},
}
