import type { ResourceConfig } from './types'
import { P, TENANT } from './types'

export const resourceConfig: ResourceConfig = {
	label: 'Application',
	description: 'Manage Intune apps, app approval, multi-tenant deployment, and licenses',
	operations: {
		getAll: {
			method: 'GET',
			endpoint: '/api/ListApps',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List applications',
		},
		getQueue: {
			method: 'GET',
			endpoint: '/api/ListApplicationQueue',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List application queue',
		},
		assign: {
			method: 'POST',
			endpoint: '/api/ExecAssignApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('App ID', true),
				AssignTo: P.bodyEnum('Assign target', ['user', 'device', 'customGroup'], true),
				GroupNames: P.body('Comma-separated group names (for customGroup)'),
			},
			description: 'Assign application',
		},
		remove: {
			method: 'POST',
			endpoint: '/api/RemoveApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('App ID to remove', true),
			},
			description: 'Remove application',
		},
		removeFromQueue: {
			method: 'POST',
			endpoint: '/api/RemoveQueuedApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('Queue item ID', true),
			},
			description: 'Remove from queue',
		},
		addWinget: {
			method: 'POST',
			endpoint: '/api/AddWinGetApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				PackageIdentifier: P.body('WinGet package ID', true),
				ApplicationName: P.body('Display name', true),
				Description: P.body('Description', true),
				AssignTo: P.bodyEnum('Assign target', ['user', 'device', 'customGroup'], true),
			},
			description: 'Add WinGet app',
		},
		addStore: {
			method: 'POST',
			endpoint: '/api/AddStoreApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				PackageName: P.body('Store package name', true),
				ApplicationName: P.body('Display name', true),
				description: P.body('Description', true),
				AssignTo: P.bodyEnum('Assign target', ['user', 'device', 'customGroup'], true),
			},
			description: 'Add Store app',
		},
		addChocolatey: {
			method: 'POST',
			endpoint: '/api/AddChocoApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				PackageName: P.body('Chocolatey package name', true),
				ApplicationName: P.body('Display name', true),
				description: P.body('Description', true),
				AssignTo: P.bodyEnum('Assign target', ['user', 'device', 'customGroup'], true),
			},
			description: 'Add Chocolatey app',
		},
		addMsp: {
			method: 'POST',
			endpoint: '/api/AddMSPApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				RMMName: P.body('RMM tool name', true),
				DisplayName: P.body('Display name', true),
				params: P.bodyJson('RMM parameters JSON', true),
				AssignTo: P.bodyEnum('Assign target', ['user', 'device', 'customGroup'], true),
			},
			description: 'Add MSP/RMM app',
		},
		addOffice: {
			method: 'POST',
			endpoint: '/api/AddOfficeApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				excludedApps: P.body('Excluded Office apps', true),
				updateChannel: P.body('Update channel', true),
				AssignTo: P.bodyEnum('Assign target', ['user', 'device', 'customGroup'], true),
			},
			description: 'Add Office app',
		},
		addWin32Script: {
			method: 'POST',
			endpoint: '/api/AddWin32ScriptApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				applicationName: P.body('App name', true),
				installScript: P.body('Install script', true),
				uninstallScript: P.body('Uninstall script', true),
				AssignTo: P.bodyEnum('Assign target', ['user', 'device', 'customGroup'], true),
				description: P.body('Description'),
			},
			description: 'Add Win32 script app',
		},
		syncVpp: {
			method: 'POST',
			endpoint: '/api/ExecSyncVPP',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {},
			description: 'Sync VPP',
		},
		triggerAppUpload: {
			method: 'GET',
			endpoint: '/api/ExecAppUpload',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'Trigger app upload',
		},
		addMultiTenantApp: {
			method: 'POST',
			endpoint: '/api/ExecAddMultiTenantApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				AppId: P.body('Application ID'),
				configMode: P.body('Configuration mode'),
				CopyPermissions: P.body('Copy permissions flag'),
			},
			description: 'Add multi-tenant app',
		},
		getAppApproval: {
			method: 'GET',
			endpoint: '/api/ExecAppApproval',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {
				ApplicationId: P.qs('Application ID'),
			},
			description: 'Get app approval',
		},
		createAppTemplate: {
			method: 'POST',
			endpoint: '/api/ExecCreateAppTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				AppId: P.body('App ID'),
				DisplayName: P.body('Template display name'),
			},
			description: 'Create app template',
		},
		listAppApprovalTemplates: {
			method: 'GET',
			endpoint: '/api/ListAppApprovalTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {},
			description: 'List app approval templates',
		},
		deleteAppApprovalTemplate: {
			method: 'DELETE',
			endpoint: '/api/ExecAppApprovalTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				TemplateId: P.body('Template ID'),
				TemplateName: P.body('Template name'),
				Action: P.body('Action'),
			},
			description: 'Delete app approval template',
		},
		listAppIds: {
			method: 'GET',
			endpoint: '/api/ExecListAppId',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'List app IDs',
		},
		patchApplication: {
			method: 'PATCH',
			endpoint: '/api/ExecApplication',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				Action: P.body('Action'),
				AppId: P.body('Application ID'),
				Id: P.body('Entity ID'),
				Type: P.body('Type'),
			},
			description: 'Patch application',
		},
		listExcludedLicenses: {
			method: 'GET',
			endpoint: '/api/ListExcludedLicenses',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {},
			description: 'List excluded licenses',
		},
		excludeLicenses: {
			method: 'POST',
			endpoint: '/api/ExecExcludeLicenses',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				Action: P.body('Action'),
				GUID: P.body('License GUID'),
				SKUName: P.body('SKU name'),
			},
			description: 'Exclude licenses',
		},
		listPotentialApps: {
			method: 'POST',
			endpoint: '/api/ListPotentialApps',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				applicationName: P.body('App name filter'),
				searchQuery: P.body('Search query'),
				type: P.body('App type filter'),
			},
			description: 'List potential apps',
		},
		listAppsRepository: {
			method: 'POST',
			endpoint: '/api/ListAppsRepository',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				Search: P.body('Search term'),
				Repository: P.body('Repository filter'),
			},
			description: 'List apps repository',
		},
	},
}
