import type { ResourceConfig } from './types'
import { P, TENANT } from './types'

export const resourceConfig: ResourceConfig = {
	label: 'Autopilot',
	description: 'Manage Windows Autopilot devices, configs, and enrollment',
	operations: {
		getAll: {
			method: 'GET',
			endpoint: '/api/ListAPDevices',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List Autopilot devices',
		},
		assign: {
			method: 'POST',
			endpoint: '/api/ExecAssignAPDevice',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				device: P.body('Device ID', true),
				serialNumber: P.body('Serial number', true),
				user: P.body('User UPN', true),
			},
			description: 'Assign AP device',
		},
		remove: {
			method: 'POST',
			endpoint: '/api/RemoveAPDevice',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('Device ID', true),
			},
			description: 'Remove AP device',
		},
		sync: {
			method: 'POST',
			endpoint: '/api/ExecSyncAPDevices',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {},
			description: 'Sync AP devices',
		},
		getConfigurations: {
			method: 'GET',
			endpoint: '/api/ListAutopilotconfig',
			isWrite: false,
			isList: false,
			tenant: TENANT.qs,
			params: {
				type: P.qs('Config type', true),
			},
			description: 'Get AP configurations',
		},
		syncDep: {
			method: 'POST',
			endpoint: '/api/ExecSyncDEP',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {},
			description: 'Sync DEP',
		},
		addDevice: {
			method: 'POST',
			endpoint: '/api/AddAPDevice',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				autopilotData: P.body('Autopilot data'),
				Groupname: P.body('Group name'),
			},
			description: 'Add AP device',
		},
		addConfig: {
			method: 'POST',
			endpoint: '/api/AddAutopilotConfig',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				DisplayName: P.body('Display name', true),
				Description: P.body('Description'),
				DeviceNameTemplate: P.body('Device name template'),
			},
			description: 'Add AP config',
		},
		addEnrollment: {
			method: 'POST',
			endpoint: '/api/AddEnrollment',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				AllowFail: P.bodyBool('Allow failure'),
				AllowReset: P.bodyBool('Allow reset'),
				blockDevice: P.bodyBool('Block device'),
				ShowProgress: P.bodyBool('Show progress'),
			},
			description: 'Add enrollment',
		},
		renameDevice: {
			method: 'POST',
			endpoint: '/api/ExecRenameAPDevice',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				deviceId: P.body('Device ID'),
				serialNumber: P.body('Serial number'),
				displayName: P.body('New display name', true),
			},
			description: 'Rename AP device',
		},
		setGroupTag: {
			method: 'POST',
			endpoint: '/api/ExecSetAPDeviceGroupTag',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				deviceId: P.body('Device ID'),
				serialNumber: P.body('Serial number'),
				groupTag: P.body('Group tag', true),
			},
			description: 'Set group tag',
		},
		removeConfig: {
			method: 'POST',
			endpoint: '/api/RemoveAutopilotConfig',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('Config ID', true),
			},
			description: 'Remove AP config',
		},
	},
}
