import type { ResourceConfig } from './types'
import { P, TENANT } from './types'

export const resourceConfig: ResourceConfig = {
	label: 'CIPP Admin',
	description: 'CIPP platform settings, setup, and extension management',
	operations: {
		createSamApp: {
			method: 'POST',
			endpoint: '/api/ExecCreateSAMApp',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				access_token: P.body('Access token', true),
			},
			description: 'Create SAM application',
		},
		runCombinedSetup: {
			method: 'POST',
			endpoint: '/api/ExecCombinedSetup',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				applicationId: P.body('App ID'),
				applicationSecret: P.body('App secret'),
				email: P.body('Email'),
				tenantid: P.body('Tenant ID'),
			},
			description: 'Run combined setup',
		},
		runSamSetup: {
			method: 'POST',
			endpoint: '/api/ExecSAMSetup',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				step: P.qs('Setup step'),
				CreateSAM: P.qs('Create SAM flag'),
				applicationid: P.body('App ID'),
				applicationsecret: P.body('App secret'),
			},
			description: 'Run SAM setup',
		},
		setBackupRetention: {
			method: 'POST',
			endpoint: '/api/ExecBackupRetentionConfig',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				List: P.qs('List flag'),
				RetentionDays: P.bodyNum('Retention days'),
			},
			description: 'Set backup retention config',
		},
		setBranding: {
			method: 'POST',
			endpoint: '/api/ExecBrandingSettings',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				Action: P.body('Action'),
				colour: P.body('Brand colour'),
				logo: P.body('Logo URL'),
			},
			description: 'Set branding settings',
		},
		setDnsConfig: {
			method: 'POST',
			endpoint: '/api/ExecDnsConfig',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				Action: P.body('Action'),
				Domain: P.body('Domain'),
				Resolver: P.body('DNS resolver'),
				Selector: P.body('DKIM selector'),
			},
			description: 'Set DNS configuration',
		},
		setExtensionsConfig: {
			method: 'POST',
			endpoint: '/api/ExecExtensionsConfig',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				Hudu: P.body('Hudu config'),
				NinjaOne: P.body('NinjaOne config'),
			},
			description: 'Set extensions configuration',
		},
		setJitAdminSettings: {
			method: 'POST',
			endpoint: '/api/ExecJITAdminSettings',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				Action: P.body('Action'),
				MaxDuration: P.body('Max duration'),
			},
			description: 'Set JIT admin settings',
		},
		setLogRetention: {
			method: 'POST',
			endpoint: '/api/ExecLogRetentionConfig',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				List: P.qs('List flag'),
				RetentionDays: P.bodyNum('Retention days'),
			},
			description: 'Set log retention config',
		},
		setNotificationConfig: {
			method: 'POST',
			endpoint: '/api/ExecNotificationConfig',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				email: P.body('Email'),
				webhook: P.body('Webhook URL'),
			},
			description: 'Set notification configuration',
		},
		setPasswordConfig: {
			method: 'POST',
			endpoint: '/api/ExecPasswordConfig',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				List: P.qs('List flag'),
				passwordType: P.body('Password type'),
			},
			description: 'Set password configuration',
		},
		setTimeSettings: {
			method: 'POST',
			endpoint: '/api/ExecTimeSettings',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				BusinessHoursStart: P.bodyJson('Business hours start'),
				Timezone: P.bodyJson('Timezone'),
			},
			description: 'Set time settings',
		},
		getExtensionCacheData: {
			method: 'POST',
			endpoint: '/api/ListExtensionCacheData',
			isWrite: false,
			isList: false,
			tenant: TENANT.body,
			params: {
				dataTypes: P.body('Data types to cache'),
			},
			description: 'Get extension cache data',
		},
		getExtensionMapping: {
			method: 'GET',
			endpoint: '/api/ExecExtensionMapping',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {
				AddMapping: P.qs('Add mapping'),
				AutoMapping: P.qs('Auto mapping'),
				List: P.qs('List flag'),
			},
			description: 'Get extension mapping',
		},
		getExtensionsConfig: {
			method: 'GET',
			endpoint: '/api/ListExtensionsConfig',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'Get extensions configuration',
		},
		getNinjaOneQueue: {
			method: 'GET',
			endpoint: '/api/ExecExtensionNinjaOneQueue',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'Get NinjaOne queue',
		},
		listExtensionSync: {
			method: 'GET',
			endpoint: '/api/ListExtensionSync',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'List extension sync status',
		},
		syncExtension: {
			method: 'GET',
			endpoint: '/api/ExecExtensionSync',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				Extension: P.qs('Extension name'),
				TenantID: P.qs('Tenant ID'),
			},
			description: 'Sync extension',
		},
		testExtension: {
			method: 'GET',
			endpoint: '/api/ExecExtensionTest',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {
				extensionName: P.qs('Extension name'),
			},
			description: 'Test extension',
		},
		refreshCpvPermissions: {
			method: 'POST',
			endpoint: '/api/ExecCPVPermissions',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ResetSP: P.qs('Reset service principal'),
			},
			description: 'Refresh CPV consent permissions for a tenant',
		},
		refreshCpvAll: {
			method: 'GET',
			endpoint: '/api/ExecCPVRefresh',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'Trigger bulk CPV refresh for all tenants',
		},
		managePartnerWebhook: {
			method: 'POST',
			endpoint: '/api/ExecPartnerWebhook',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				Action: P.qs('Webhook action'),
				CorrelationId: P.qs('Correlation ID'),
				enabled: P.bodyBool('Enable webhook'),
				EventType: P.body('Event type'),
				standardsExcludeAllTenants: P.bodyBool('Exclude all tenants from standards'),
			},
			description: 'Manage partner webhook subscriptions',
		},
		listPendingWebhooks: {
			method: 'GET',
			endpoint: '/api/ListPendingWebhooks',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {},
			description: 'List pending webhook deliveries',
		},
		listExtAlerts: {
			method: 'GET',
			endpoint: '/api/ListCheckExtAlerts',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List extension alert monitoring results',
		},
	},
}
