import type { ResourceConfig } from './types'
import { P, TENANT } from './types'

export const resourceConfig: ResourceConfig = {
	label: 'Mailbox',
	description: 'Manage Exchange mailboxes, permissions, rules, forwarding, and retention',
	operations: {
		listMailboxes: {
			method: 'GET',
			endpoint: '/api/ListMailboxes',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List all mailboxes',
		},
		listMailboxPermissions: {
			method: 'GET',
			endpoint: '/api/ListmailboxPermissions',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				userId: P.qs('Filter by user ID'),
			},
			description: 'List mailbox permissions',
		},
		listCalendarPermissions: {
			method: 'GET',
			endpoint: '/api/ListCalendarPermissions',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				UserID: P.qs('Filter by user ID'),
			},
			description: 'List calendar permissions',
		},
		listMailboxRules: {
			method: 'GET',
			endpoint: '/api/ListMailboxRules',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List mailbox rules',
		},
		listMobileDevices: {
			method: 'GET',
			endpoint: '/api/ListMailboxMobileDevices',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				Mailbox: P.qs('Mailbox filter'),
			},
			description: 'List mailbox mobile devices',
		},
		listOutOfOffice: {
			method: 'GET',
			endpoint: '/api/ListOoO',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				userid: P.qs('Filter by user ID'),
			},
			description: 'List out-of-office settings',
		},
		listRestrictedUsers: {
			method: 'GET',
			endpoint: '/api/ListRestrictedUsers',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List restricted users',
		},
		listGlobalAddressList: {
			method: 'GET',
			endpoint: '/api/ListGlobalAddressList',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List global address list',
		},
		listMailboxCAS: {
			method: 'GET',
			endpoint: '/api/ListMailboxCAS',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List mailbox CAS settings',
		},
		listSharedMailboxAccountEnabled: {
			method: 'GET',
			endpoint: '/api/ListSharedMailboxAccountEnabled',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List shared mailboxes with account enabled',
		},
		listSharedMailboxStats: {
			method: 'GET',
			endpoint: '/api/ListSharedMailboxStatistics',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List shared mailbox statistics',
		},
		listMailboxRestores: {
			method: 'GET',
			endpoint: '/api/ListMailboxRestores',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				Identity: P.qs('Identity'),
				IncludeReport: P.qsBool('Include report'),
				Statistics: P.qsBool('Include stats'),
			},
			description: 'List mailbox restores',
		},
		listMessageTrace: {
			method: 'POST',
			endpoint: '/api/ListMessageTrace',
			isWrite: false,
			isList: true,
			tenant: TENANT.body,
			params: {
				dateFilter: P.bodyEnum('Date filter type', ['relative', 'custom'], true),
				days: P.bodyNum('Days (for relative)'),
				startDate: P.body('Start date (for custom)'),
				endDate: P.body('End date (for custom)'),
			},
			description: 'List message trace results',
		},
		runExoRequest: {
			method: 'POST',
			endpoint: '/api/ListExoRequest',
			isWrite: false,
			isList: true,
			tenant: TENANT.bodyPascal,
			params: {
				Cmdlet: P.body('Exchange cmdlet', true),
				Select: P.body('Fields to select'),
				Compliance: P.bodyBool('Compliance mode'),
			},
			description: 'Run an Exchange Online request',
		},
		addSharedMailbox: {
			method: 'POST',
			endpoint: '/api/AddSharedMailbox',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyTenantID,
			params: {
				displayName: P.body('Display name', true),
				username: P.body('Username', true),
				domain: P.body('Domain', true),
				addedAliases: P.body('Aliases'),
			},
			description: 'Add a shared mailbox',
		},
		createHighVolumeEmail: {
			method: 'POST',
			endpoint: '/api/ExecHVEUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				displayName: P.body('Display name', true),
				primarySMTPAddress: P.body('SMTP address', true),
				password: P.body('Password', true),
			},
			description: 'Create a high-volume email user',
		},
		removeRestrictedUser: {
			method: 'POST',
			endpoint: '/api/ExecRemoveRestrictedUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				SenderAddress: P.body('Sender address', true),
			},
			description: 'Remove a restricted user',
		},
		restoreMailbox: {
			method: 'POST',
			endpoint: '/api/ExecMailboxRestore',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				SourceMailbox: P.body('Source mailbox', true),
				TargetMailbox: P.body('Target mailbox', true),
			},
			description: 'Restore a mailbox',
		},
		manageRetentionPolicies: {
			method: 'DELETE',
			endpoint: '/api/ExecManageRetentionPolicies',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				name: P.qs('Policy name'),
				CreatePolicies: P.bodyJson('Create policies JSON'),
				ModifyPolicies: P.bodyJson('Modify policies JSON'),
				DeletePolicies: P.bodyJson('Delete policies JSON'),
			},
			description: 'Manage retention policies',
		},
		manageRetentionTags: {
			method: 'DELETE',
			endpoint: '/api/ExecManageRetentionTags',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				name: P.qs('Tag name'),
				CreateTags: P.bodyJson('Create tags JSON'),
				ModifyTags: P.bodyJson('Modify tags JSON'),
				DeleteTags: P.bodyJson('Delete tags JSON'),
			},
			description: 'Manage retention tags',
		},
		setMailboxRetentionPolicies: {
			method: 'POST',
			endpoint: '/api/ExecSetMailboxRetentionPolicies',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				Mailboxes: P.body('Mailbox IDs', true),
				PolicyName: P.body('Policy name', true),
			},
			description: 'Set mailbox retention policies',
		},
		convert: {
			method: 'POST',
			endpoint: '/api/ExecConvertMailbox',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User/mailbox ID', true),
				MailboxType: P.body('Target type', true),
			},
			description: 'Convert mailbox type',
		},
		enableArchive: {
			method: 'POST',
			endpoint: '/api/ExecEnableArchive',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				id: P.body('User/mailbox ID', true),
			},
			description: 'Enable mailbox archive',
		},
		setOutOfOffice: {
			method: 'POST',
			endpoint: '/api/ExecSetOoO',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userId: P.body('User ID', true),
				AutoReplyState: P.bodyEnum('Auto-reply state', ['Enabled', 'Disabled', 'Scheduled'], true),
				input: P.body('Reply message'),
			},
			description: 'Set out-of-office settings',
		},
		setForwarding: {
			method: 'POST',
			endpoint: '/api/ExecEmailForward',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userID: P.body('User ID', true),
				forwardOption: P.bodyEnum('Forward option', ['internal', 'external', 'disabled'], true),
				KeepCopy: P.body('Keep copy (true/false)'),
				ForwardInternal: P.body('Internal forward address'),
				ForwardExternal: P.body('External forward address'),
			},
			description: 'Set mailbox forwarding',
		},
		editMailboxPermissions: {
			method: 'POST',
			endpoint: '/api/ExecEditMailboxPermissions',
			isWrite: true,
			isList: false,
			tenant: { location: 'body' as const, field: 'tenantfilter' },
			params: {
				userID: P.body('User ID', true),
			},
			description: 'Edit mailbox permissions',
		},
		editCalendarPermissions: {
			method: 'POST',
			endpoint: '/api/ExecEditCalendarPermissions',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userid: P.body('User ID', true),
				UserToGetPermissions: P.body('Target user', true),
				Permissions: P.body('Permission level', true),
			},
			description: 'Edit calendar permissions',
		},
		setDefaultCalendarPerms: {
			method: 'POST',
			endpoint: '/api/ExecModifyCalPerms',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userID: P.body('User ID', true),
				permissions: P.body('Permission level', true),
			},
			description: 'Set default calendar permissions',
		},
		setDefaultContactPerms: {
			method: 'POST',
			endpoint: '/api/ExecModifyContactPerms',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userID: P.body('User ID', true),
				permissions: P.body('Permission level', true),
			},
			description: 'Set default contact permissions',
		},
		setDefaultMailboxPerms: {
			method: 'POST',
			endpoint: '/api/ExecModifyMBPerms',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userID: P.body('User ID', true),
				permissions: P.body('Permission level', true),
			},
			description: 'Set default mailbox permissions',
		},
		setMailboxQuota: {
			method: 'POST',
			endpoint: '/api/ExecSetMailboxQuota',
			isWrite: true,
			isList: false,
			tenant: { location: 'body' as const, field: 'tenantfilter' },
			params: {
				user: P.body('User ID', true),
			},
			description: 'Set mailbox quota',
		},
		setEmailSize: {
			method: 'POST',
			endpoint: '/api/ExecSetMailboxEmailSize',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				UPN: P.body('User UPN', true),
				maxSendSize: P.body('Max send size', true),
				maxReceiveSize: P.body('Max receive size', true),
			},
			description: 'Set mailbox email size limits',
		},
		setLocale: {
			method: 'POST',
			endpoint: '/api/ExecSetMailboxLocale',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				user: P.body('User ID', true),
				locale: P.body('Locale code', true),
			},
			description: 'Set mailbox locale',
		},
		setMailboxRule: {
			method: 'POST',
			endpoint: '/api/ExecSetMailboxRule',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				userPrincipalName: P.body('User UPN', true),
				ruleName: P.body('Rule name', true),
				ruleId: P.body('Rule ID'),
				Enable: P.body('Enable flag'),
				Disable: P.body('Disable flag'),
			},
			description: 'Set mailbox rule',
		},
		removeMailboxRule: {
			method: 'POST',
			endpoint: '/api/ExecRemoveMailboxRule',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				userPrincipalName: P.body('User UPN', true),
				ruleName: P.body('Rule name', true),
				ruleId: P.body('Rule ID'),
			},
			description: 'Remove mailbox rule',
		},
		setRecipientLimits: {
			method: 'POST',
			endpoint: '/api/ExecSetRecipientLimits',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userid: P.body('User ID', true),
				recipientLimit: P.body('Recipient limit', true),
			},
			description: 'Set recipient limits',
		},
		setCopyForSent: {
			method: 'POST',
			endpoint: '/api/ExecCopyForSent',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
				messageCopyState: P.body('Copy state', true),
			},
			description: 'Set copy-for-sent behavior',
		},
		setCalendarProcessing: {
			method: 'POST',
			endpoint: '/api/ExecSetCalendarProcessing',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				UPN: P.body('User UPN', true),
			},
			description: 'Set calendar processing options',
		},
		setLitigationHold: {
			method: 'POST',
			endpoint: '/api/ExecSetLitigationHold',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				UPN: P.body('User UPN', true),
				days: P.body('Hold duration in days'),
			},
			description: 'Set litigation hold',
		},
		setRetentionHold: {
			method: 'POST',
			endpoint: '/api/ExecSetRetentionHold',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				UPN: P.body('User UPN', true),
			},
			description: 'Set retention hold',
		},
		startManagedFolderAssistant: {
			method: 'POST',
			endpoint: '/api/ExecStartManagedFolderAssistant',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				UserPrincipalName: P.body('User UPN', true),
			},
			description: 'Start managed folder assistant',
		},
		enableAutoExpandArchive: {
			method: 'POST',
			endpoint: '/api/ExecEnableAutoExpandingArchive',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
			},
			description: 'Enable auto-expanding archive',
		},
		hideFromGAL: {
			method: 'POST',
			endpoint: '/api/ExecHideFromGAL',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
				HideFromGAL: P.body('Hide flag', true),
			},
			description: 'Hide or show mailbox in global address list',
		},
		manageMobileDevice: {
			method: 'GET',
			endpoint: '/api/ExecMailboxMobileDevices',
			isWrite: true,
			isList: false,
			tenant: TENANT.qs,
			params: {
				Userid: P.qs('User ID', true),
				deviceid: P.qs('Device ID', true),
				Delete: P.qsBool('Delete device'),
				Quarantine: P.qsBool('Quarantine device'),
			},
			description: 'Manage mailbox mobile device',
		},
		repairExchangeRole: {
			method: 'POST',
			endpoint: '/api/ExecExchangeRoleRepair',
			isWrite: true,
			isList: false,
			tenant: { location: 'body' as const, field: 'tenantId' },
			params: {},
			description: 'Repair Exchange role',
		},
		sendOrgMessage: {
			method: 'GET',
			endpoint: '/api/ExecSendOrgMessage',
			isWrite: true,
			isList: false,
			tenant: TENANT.qs,
			params: {
				ID: P.qs('Message ID'),
				freq: P.qs('Frequency'),
				type: P.qs('Message type'),
				URL: P.qs('URL'),
			},
			description: 'Send organization message',
		},
	},
}
