import type { ResourceConfig } from './types'
import { P, TENANT } from './types'

export const resourceConfig: ResourceConfig = {
	label: 'Policy',
	description: 'Manage Intune policies, assignment filters, templates, scripts, and Defender',
	operations: {
		getMany: {
			method: 'GET',
			endpoint: '/api/ListIntunePolicy',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List Intune policies',
		},
		add: {
			method: 'POST',
			endpoint: '/api/AddPolicy',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				policyConfig: P.bodyJson('Policy config JSON', true),
			},
			description: 'Add a policy',
		},
		assign: {
			method: 'POST',
			endpoint: '/api/ExecAssignPolicy',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('Policy ID', true),
				AssignTo: P.bodyEnum('Target', ['user', 'device', 'customGroup'], true),
				GroupNames: P.body('Group names (for customGroup)'),
			},
			description: 'Assign a policy',
		},
		remove: {
			method: 'POST',
			endpoint: '/api/RemovePolicy',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('Policy ID', true),
			},
			description: 'Remove a policy',
		},
		listDefenderTvm: {
			method: 'GET',
			endpoint: '/api/ListDefenderTVM',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List Defender TVM data',
		},
		listAssignmentFilters: {
			method: 'GET',
			endpoint: '/api/ListAssignmentFilters',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				filterId: P.qs('Filter ID'),
			},
			description: 'List assignment filters',
		},
		addAssignmentFilter: {
			method: 'POST',
			endpoint: '/api/AddAssignmentFilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				displayName: P.body('Display name', true),
				description: P.body('Description'),
				platform: P.body('Platform'),
				rule: P.body('Filter rule'),
			},
			description: 'Add an assignment filter',
		},
		editAssignmentFilter: {
			method: 'POST',
			endpoint: '/api/EditAssignmentFilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				filterId: P.body('Filter ID', true),
				displayName: P.body('Display name'),
				description: P.body('Description'),
				platform: P.body('Platform'),
				rule: P.body('Rule'),
			},
			description: 'Edit an assignment filter',
		},
		deleteAssignmentFilter: {
			method: 'DELETE',
			endpoint: '/api/ExecAssignmentFilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('Filter ID', true),
			},
			description: 'Delete an assignment filter',
		},
		listAssignmentFilterTemplates: {
			method: 'GET',
			endpoint: '/api/ListAssignmentFilterTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				ID: P.qs('Template ID'),
			},
			description: 'List assignment filter templates',
		},
		addAssignmentFilterTemplate: {
			method: 'POST',
			endpoint: '/api/AddAssignmentFilterTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				displayname: P.body('Display name', true),
				Description: P.body('Description'),
				platform: P.body('Platform'),
				rule: P.body('Rule'),
			},
			description: 'Add an assignment filter template',
		},
		removeAssignmentFilterTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveAssignmentFilterTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove an assignment filter template',
		},
		listIntuneTemplates: {
			method: 'GET',
			endpoint: '/api/ListIntuneTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				id: P.qs('Template ID'),
				mode: P.qs('Mode'),
				View: P.qs('View'),
			},
			description: 'List Intune templates',
		},
		addIntuneTemplate: {
			method: 'POST',
			endpoint: '/api/AddIntuneTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				RawJSON: P.body('Raw JSON config', true),
				displayName: P.body('Display name'),
				TemplateType: P.body('Template type'),
			},
			description: 'Add an Intune template',
		},
		removeIntuneTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveIntuneTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove an Intune template',
		},
		listIntuneScripts: {
			method: 'GET',
			endpoint: '/api/ListIntuneScript',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List Intune scripts',
		},
		editIntuneScript: {
			method: 'PATCH',
			endpoint: '/api/EditIntuneScript',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				ScriptId: P.body('Script ID', true),
				IntuneScript: P.body('Script content'),
				ScriptType: P.body('Script type'),
			},
			description: 'Edit an Intune script',
		},
		removeIntuneScript: {
			method: 'POST',
			endpoint: '/api/RemoveIntuneScript',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				ID: P.body('Script ID', true),
				DisplayName: P.body('Display name'),
				ScriptType: P.body('Script type'),
			},
			description: 'Remove an Intune script',
		},
		listReusableSettings: {
			method: 'GET',
			endpoint: '/api/ListIntuneReusableSettings',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				ID: P.qs('Setting ID'),
			},
			description: 'List Intune reusable settings',
		},
		addReusableSetting: {
			method: 'POST',
			endpoint: '/api/AddIntuneReusableSetting',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				rawJSON: P.body('Raw JSON', true),
				displayName: P.body('Display name'),
				description: P.body('Description'),
			},
			description: 'Add an Intune reusable setting',
		},
		removeReusableSetting: {
			method: 'POST',
			endpoint: '/api/RemoveIntuneReusableSetting',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('Setting ID', true),
			},
			description: 'Remove an Intune reusable setting',
		},
		listReusableSettingTemplates: {
			method: 'GET',
			endpoint: '/api/ListIntuneReusableSettingTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				ID: P.qs('Template ID'),
			},
			description: 'List Intune reusable setting templates',
		},
		addReusableSettingTemplate: {
			method: 'POST',
			endpoint: '/api/AddIntuneReusableSettingTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				rawJSON: P.body('Raw JSON', true),
				displayName: P.body('Display name', true),
				description: P.body('Description'),
			},
			description: 'Add an Intune reusable setting template',
		},
		removeReusableSettingTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveIntuneReusableSettingTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove an Intune reusable setting template',
		},
		editPolicy: {
			method: 'POST',
			endpoint: '/api/EditPolicy',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyLower,
			params: {
				Displayname: P.body('Display name'),
				Description: P.body('Description'),
				Assignto: P.body('Assign to'),
				groupid: P.body('Group ID'),
			},
			description: 'Edit a policy',
		},
		editIntunePolicy: {
			method: 'POST',
			endpoint: '/api/EditIntunePolicy',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('Policy ID', true),
				newDisplayName: P.body('New name'),
				policyType: P.body('Policy type'),
			},
			description: 'Edit an Intune policy',
		},
		listCompliancePolicies: {
			method: 'GET',
			endpoint: '/api/ListCompliancePolicies',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List compliance policies',
		},
		listAppProtectionPolicies: {
			method: 'GET',
			endpoint: '/api/ListAppProtectionPolicies',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List app protection policies',
		},
		listDefenderState: {
			method: 'GET',
			endpoint: '/api/ListDefenderState',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				DeviceID: P.qs('Device ID'),
			},
			description: 'List Defender state',
		},
		addDefenderDeployment: {
			method: 'POST',
			endpoint: '/api/AddDefenderDeployment',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				deploymentConfig: P.bodyJson('Deployment config JSON', true),
			},
			description: 'Add a Defender deployment',
		},
		execDevicePasscodeAction: {
			method: 'POST',
			endpoint: '/api/ExecDevicePasscodeAction',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				Action: P.body('Passcode action', true),
				GUID: P.body('Device GUID', true),
			},
			description: 'Execute a device passcode action',
		},
		listIntuneIntents: {
			method: 'GET',
			endpoint: '/api/ListIntuneIntents',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List Intune intents',
		},
	},
}
