import type { ResourceConfig } from './types'
import { P, TENANT } from './types'

export const resourceConfig: ResourceConfig = {
	label: 'Spam Filter',
	description: 'Manage spam filters, quarantine policies, allow/block lists, and email protection',
	operations: {
		listSpamfilters: {
			method: 'GET',
			endpoint: '/api/ListSpamfilter',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List spam filters',
		},
		addSpamFilter: {
			method: 'POST',
			endpoint: '/api/AddSpamFilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				TemplateList: P.bodyJson('Template JSON'),
				PowerShellCommand: P.body('PowerShell command'),
				name: P.body('Filter name'),
				Priority: P.bodyNum('Priority'),
			},
			description: 'Add a spam filter',
		},
		editSpamFilter: {
			method: 'POST',
			endpoint: '/api/EditSpamFilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				name: P.body('Filter name', true),
				state: P.body('State', true),
			},
			description: 'Edit a spam filter',
		},
		removeSpamfilter: {
			method: 'POST',
			endpoint: '/api/RemoveSpamfilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				name: P.body('Filter name', true),
			},
			description: 'Remove a spam filter',
		},
		listSpamFilterTemplates: {
			method: 'GET',
			endpoint: '/api/ListSpamFilterTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				id: P.qs('Template ID'),
			},
			description: 'List spam filter templates',
		},
		addSpamFilterTemplate: {
			method: 'POST',
			endpoint: '/api/AddSpamFilterTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				name: P.body('Template name', true),
				PowerShellCommand: P.body('PowerShell command'),
			},
			description: 'Add a spam filter template',
		},
		removeSpamFilterTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveSpamfilterTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove a spam filter template',
		},
		listQuarantinePolicies: {
			method: 'POST',
			endpoint: '/api/ListQuarantinePolicy',
			isWrite: false,
			isList: true,
			tenant: TENANT.bodyPascal,
			params: {
				Type: P.qs('Policy type filter'),
			},
			description: 'List quarantine policies',
		},
		addQuarantinePolicy: {
			method: 'POST',
			endpoint: '/api/AddQuarantinePolicy',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				Name: P.body('Policy name'),
				TemplateList: P.bodyJson('Template JSON'),
				AllowSender: P.bodyBool('Allow sender'),
				BlockSender: P.bodyBool('Block sender'),
			},
			description: 'Add a quarantine policy',
		},
		editQuarantinePolicy: {
			method: 'POST',
			endpoint: '/api/EditQuarantinePolicy',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				Identity: P.body('Policy identity', true),
			},
			description: 'Edit a quarantine policy',
		},
		removeQuarantinePolicy: {
			method: 'POST',
			endpoint: '/api/RemoveQuarantinePolicy',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				Identity: P.body('Policy identity', true),
			},
			description: 'Remove a quarantine policy',
		},
		addTenantAllowBlockList: {
			method: 'POST',
			endpoint: '/api/AddTenantAllowBlockList',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyTenantID,
			params: {
				entries: P.body('Entries', true),
				listType: P.body('List type', true),
				listMethod: P.body('List method', true),
				notes: P.body('Notes'),
			},
			description: 'Add tenant allow/block list entry',
		},
		listAntiPhishingFilters: {
			method: 'GET',
			endpoint: '/api/ListAntiPhishingFilters',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List anti-phishing filters',
		},
		listMalwareFilters: {
			method: 'GET',
			endpoint: '/api/ListMalwareFilters',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List malware filters',
		},
		listSafeAttachmentsFilters: {
			method: 'GET',
			endpoint: '/api/ListSafeAttachmentsFilters',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List safe attachments filters',
		},
		editAntiPhishingFilter: {
			method: 'POST',
			endpoint: '/api/EditAntiPhishingFilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				RuleName: P.body('Rule name', true),
				State: P.body('State', true),
			},
			description: 'Edit an anti-phishing filter',
		},
		editMalwareFilter: {
			method: 'POST',
			endpoint: '/api/EditMalwareFilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				RuleName: P.body('Rule name', true),
				State: P.body('State', true),
			},
			description: 'Edit a malware filter',
		},
		editSafeAttachmentsFilter: {
			method: 'POST',
			endpoint: '/api/EditSafeAttachmentsFilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				RuleName: P.body('Rule name', true),
				State: P.body('State', true),
			},
			description: 'Edit a safe attachments filter',
		},
	},
}
