import type { ResourceConfig } from './types';
import { P, TENANT } from './types';

export const resourceConfig: ResourceConfig = {
	label: 'Standard',
	description: 'Manage tenant standards, BPA, domain analysis, and drift',
	operations: {
		listStandards: {
			method: 'GET',
			endpoint: '/api/ListStandards',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				ShowConsolidated: P.qsBool('Show consolidated'),
			},
			description: 'List standards',
		},
		deployStandards: {
			method: 'POST',
			endpoint: '/api/AddStandardsDeploy',
			isWrite: true,
			isList: false,
			tenant: { location: 'body', field: 'tenant' },
			params: {
				standardsJson: P.bodyJson('Standards JSON config'),
			},
			description: 'Deploy standards',
		},
		addStandardsTemplate: {
			method: 'POST',
			endpoint: '/api/AddStandardsTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				templateName: P.body('Template name', true),
				GUID: P.body('Template GUID'),
			},
			description: 'Add standards template',
		},
		removeStandard: {
			method: 'GET',
			endpoint: '/api/RemoveStandard',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.qs('Standard ID', true),
			},
			description: 'Remove standard',
		},
		removeStandardTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveStandardTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove standard template',
		},
		listStandardTemplates: {
			method: 'GET',
			endpoint: '/api/listStandardTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				id: P.qs('Template ID'),
			},
			description: 'List standard templates',
		},
		runStandards: {
			method: 'GET',
			endpoint: '/api/ExecStandardsRun',
			isWrite: true,
			isList: false,
			tenant: TENANT.qs,
			params: {
				templateId: P.qs('Template ID'),
			},
			description: 'Run standards',
		},
		runAllStandards: {
			method: 'GET',
			endpoint: '/api/CIPPStandardsRun',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'Run all standards',
		},
		convertStandards: {
			method: 'GET',
			endpoint: '/api/ExecStandardConvert',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'Convert standards',
		},
		listBpa: {
			method: 'GET',
			endpoint: '/api/ListBPA',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				Report: P.qs('Report name'),
			},
			description: 'List BPA results',
		},
		listBpaResults: {
			method: 'GET',
			endpoint: '/api/BestPracticeAnalyser_List',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {},
			description: 'List BPA results (legacy)',
		},
		runBpa: {
			method: 'POST',
			endpoint: '/api/ExecBPA',
			isWrite: true,
			isList: false,
			tenant: { location: 'body', field: 'tenantfilter' },
			params: {},
			description: 'Run BPA',
		},
		listBpaTemplates: {
			method: 'GET',
			endpoint: '/api/ListBPATemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				RawJson: P.qsBool('Return raw JSON'),
			},
			description: 'List BPA templates',
		},
		addBpaTemplate: {
			method: 'POST',
			endpoint: '/api/AddBPATemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				name: P.body('Template name', true),
				style: P.body('Template style', true),
			},
			description: 'Add BPA template',
		},
		removeBpaTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveBPATemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				TemplateName: P.body('Template name', true),
			},
			description: 'Remove BPA template',
		},
		listDomainAnalyser: {
			method: 'GET',
			endpoint: '/api/ListDomainAnalyser',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List domain analyser results',
		},
		runDomainAnalyser: {
			method: 'GET',
			endpoint: '/api/ExecDomainAnalyser',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'Run domain analyser',
		},
		getDomainHealth: {
			method: 'GET',
			endpoint: '/api/ListDomainHealth',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				Domain: P.qs('Domain name', true),
				Action: P.qs('Check action'),
				ExpectedInclude: P.qs('Expected include value'),
				Record: P.qs('DNS record type'),
				Selector: P.qs('DKIM selector'),
				Subdomains: P.qs('Subdomains to check'),
			},
			description: 'Get domain health',
		},
		listTenantDrift: {
			method: 'GET',
			endpoint: '/api/ListTenantDrift',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List tenant drift',
		},
		listTenantAlignment: {
			method: 'GET',
			endpoint: '/api/ListTenantAlignment',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {},
			description: 'List tenant alignment',
		},
		cloneDrift: {
			method: 'POST',
			endpoint: '/api/ExecDriftClone',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				id: P.body('Drift config ID', true),
			},
			description: 'Clone drift configuration',
		},
		compareStandards: {
			method: 'GET',
			endpoint: '/api/ListStandardsCompare',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				templateId: P.qs('Template ID'),
			},
			description: 'Compare standards',
		},
		updateDriftDeviation: {
			method: 'POST',
			endpoint: '/api/ExecUpdateDriftDeviation',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				deviations: P.body('Deviations'),
				reason: P.body('Reason'),
				RemoveDriftCustomization: P.body('Remove drift customization ID'),
			},
			description: 'Update drift deviation',
		},
	},
};
