import type { ResourceConfig } from './types';
import { P, TENANT } from './types';

export const resourceConfig: ResourceConfig = {
	label: 'Team',
	description: 'Manage Teams, SharePoint sites, quotas, and settings',
	operations: {
		getAll: {
			method: 'GET',
			endpoint: '/api/ListTeams',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			defaults: { qs: { type: 'list' } },
			description: 'List all teams',
		},
		add: {
			method: 'POST',
			endpoint: '/api/AddTeam',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyLower,
			params: {
				displayName: P.body('Team name', true),
				description: P.body('Description', true),
				owner: P.body('Owner UPN', true),
				visibility: P.bodyEnum('Visibility', ['Public', 'Private'], true),
			},
			description: 'Add a team',
		},
		getSites: {
			method: 'GET',
			endpoint: '/api/ListSites',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				Type: P.qs('Site type', true),
			},
			description: 'List SharePoint sites',
		},
		addSite: {
			method: 'POST',
			endpoint: '/api/AddSite',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				siteName: P.body('Site name', true),
				siteDescription: P.body('Description', true),
				siteOwner: P.body('Owner UPN', true),
				templateName: P.bodyEnum('Template', ['team', 'communication'], true),
				siteDesign: P.body('Site design (for communication)'),
			},
			description: 'Add SharePoint site',
		},
		getActivity: {
			method: 'GET',
			endpoint: '/api/ListTeamsActivity',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			defaults: { qs: { Type: 'TeamsUserActivityUser' } },
			description: 'List Teams activity',
		},
		manageSiteMember: {
			method: 'POST',
			endpoint: '/api/ExecSetSharePointMember',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				URL: P.body('Site URL', true),
				Add: P.bodyBool('Add member (true) or remove (false)', true),
				user: P.body('User UPN', true),
			},
			description: 'Manage SharePoint site member',
		},
		manageSitePermissions: {
			method: 'POST',
			endpoint: '/api/ExecSharePointPerms',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				URL: P.body('Site URL', true),
				RemovePermission: P.bodyBool('Remove permission'),
				user: P.body('User UPN', true),
			},
			description: 'Manage SharePoint site permissions',
		},
		deleteSite: {
			method: 'POST',
			endpoint: '/api/DeleteSharepointSite',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				SiteId: P.body('Site ID', true),
			},
			description: 'Delete SharePoint site',
		},
		getAdminUrl: {
			method: 'GET',
			endpoint: '/api/ListSharepointAdminUrl',
			isWrite: false,
			isList: false,
			tenant: TENANT.qs,
			params: {
				ReturnUrl: P.qsBool('Return URL only'),
			},
			description: 'Get SharePoint admin URL',
		},
		getSharepointQuota: {
			method: 'GET',
			endpoint: '/api/ListSharepointQuota',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'Get SharePoint quota',
		},
		getSharepointSettings: {
			method: 'GET',
			endpoint: '/api/ListSharepointSettings',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'Get SharePoint settings',
		},
		addSitesBulk: {
			method: 'POST',
			endpoint: '/api/AddSiteBulk',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				bulkSites: P.bodyJson('Bulk sites config JSON', true),
			},
			description: 'Add SharePoint sites in bulk',
		},
	},
};
