import type { ResourceConfig } from './types';
import { P, TENANT } from './types';

export const resourceConfig: ResourceConfig = {
	label: 'Tools',
	description: 'Breach search, Graph requests, GeoIP, and universal search',
	operations: {
		breachAccount: {
			method: 'GET',
			endpoint: '/api/ListBreachesAccount',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {
				account: P.qs('Email or account to check', true),
			},
			description: 'Check breaches for account',
		},
		breachTenant: {
			method: 'GET',
			endpoint: '/api/ListBreachesTenant',
			isWrite: false,
			isList: false,
			tenant: TENANT.qs,
			params: {},
			description: 'Check breaches for tenant',
		},
		executeBreachSearch: {
			method: 'POST',
			endpoint: '/api/ExecBreachSearch',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {},
			description: 'Execute breach search',
		},
		graphRequest: {
			method: 'GET',
			endpoint: '/api/ListGraphRequest',
			isWrite: false,
			isList: false,
			tenant: TENANT.qs,
			params: {
				Endpoint: P.qs('Graph endpoint path', true),
				$select: P.qs('Fields to select'),
				$filter: P.qs('OData filter'),
				$orderby: P.qs('Order by'),
				$top: P.qsNum('Max results'),
				$count: P.qsBool('Include count'),
			},
			description: 'Execute Graph API GET request',
		},
		execGraphRequest: {
			method: 'POST',
			endpoint: '/api/ExecGraphRequest',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				endpoint: P.body('Graph endpoint path', true),
				method: P.bodyEnum('HTTP method', ['GET', 'POST', 'PATCH', 'DELETE'], true),
				body: P.bodyJson('Request body JSON'),
			},
			description: 'Execute Graph API request',
		},
		graphRequestExec: {
			method: 'POST',
			endpoint: '/api/ExecGraphRequest',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				endpoint: P.body('Graph endpoint path', true),
				method: P.bodyEnum('HTTP method', ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'], true),
				headers: P.bodyJson('Custom headers JSON'),
				body: P.bodyJson('Request body JSON'),
			},
			description: 'Execute Graph API request (extended)',
		},
		sendTestEmail: {
			method: 'GET',
			endpoint: '/api/ExecMailTest',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'Send test email',
		},
		geoIpLookup: {
			method: 'POST',
			endpoint: '/api/ExecGeoIPLookup',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {
				IP: P.body('IP address', true),
			},
			description: 'GeoIP lookup',
		},
		universalSearch: {
			method: 'GET',
			endpoint: '/api/ExecUniversalSearch',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {
				name: P.qs('Search term'),
			},
			description: 'Universal search',
		},
		universalSearchV2: {
			method: 'GET',
			endpoint: '/api/ExecUniversalSearchV2',
			isWrite: false,
			isList: false,
			tenant: TENANT.none,
			params: {
				searchTerms: P.qs('Search terms'),
				type: P.qs('Search type'),
				limit: P.qsNum('Max results'),
			},
			description: 'Universal search v2',
		},
		listAllTenantDeviceCompliance: {
			method: 'GET',
			endpoint: '/api/ListAllTenantDeviceCompliance',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List all tenant device compliance',
		},
	},
};
