import type { ResourceConfig } from './types';
import { P, TENANT } from './types';

export const resourceConfig: ResourceConfig = {
	label: 'Transport',
	description: 'Manage Exchange transport rules, connectors, and connection filters',
	operations: {
		listRules: {
			method: 'GET',
			endpoint: '/api/ListTransportRules',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List Exchange transport rules for a tenant',
		},
		addRule: {
			method: 'POST',
			endpoint: '/api/AddTransportRule',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				PowerShellCommand: P.body('PowerShell command'),
				name: P.body('Rule name'),
				TemplateList: P.bodyJson('Template JSON'),
			},
			description: 'Add a transport rule to a tenant',
		},
		addEditRule: {
			method: 'POST',
			endpoint: '/api/AddEditTransportRule',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				name: P.body('Rule name', true),
				Enabled: P.bodyBool('Enabled', true),
				Comments: P.body('Comments'),
			},
			description: 'Add or edit a transport rule',
		},
		editRule: {
			method: 'POST',
			endpoint: '/api/EditTransportRule',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				guid: P.body('Rule GUID', true),
				state: P.body('State', true),
			},
			description: 'Edit the state of a transport rule',
		},
		removeRule: {
			method: 'POST',
			endpoint: '/api/RemoveTransportRule',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				guid: P.body('Rule GUID', true),
			},
			description: 'Remove a transport rule from a tenant',
		},
		listRuleTemplates: {
			method: 'GET',
			endpoint: '/api/ListTransportRulesTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				id: P.qs('Template ID'),
			},
			description: 'List transport rule templates',
		},
		addRuleTemplate: {
			method: 'POST',
			endpoint: '/api/AddTransportTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				name: P.body('Template name', true),
				PowerShellCommand: P.body('PowerShell command'),
			},
			description: 'Add a transport rule template',
		},
		removeRuleTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveTransportRuleTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove a transport rule template',
		},
		listConnectors: {
			method: 'GET',
			endpoint: '/api/ListExchangeConnectors',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List Exchange connectors for a tenant',
		},
		addConnector: {
			method: 'POST',
			endpoint: '/api/AddExConnector',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				PowerShellCommand: P.body('PowerShell command'),
				comment: P.body('Comment'),
				TemplateList: P.bodyJson('Template JSON'),
			},
			description: 'Add an Exchange connector to a tenant',
		},
		editConnector: {
			method: 'POST',
			endpoint: '/api/EditExConnector',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				GUID: P.body('Connector GUID', true),
				State: P.body('State', true),
				Type: P.body('Connector type'),
			},
			description: 'Edit the state of an Exchange connector',
		},
		removeConnector: {
			method: 'POST',
			endpoint: '/api/RemoveExConnector',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				GUID: P.body('Connector GUID', true),
				Type: P.body('Connector type'),
			},
			description: 'Remove an Exchange connector from a tenant',
		},
		listConnectorTemplates: {
			method: 'GET',
			endpoint: '/api/ListExConnectorTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				id: P.qs('Template ID'),
			},
			description: 'List Exchange connector templates',
		},
		addConnectorTemplate: {
			method: 'POST',
			endpoint: '/api/AddExConnectorTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				name: P.body('Template name', true),
				cippconnectortype: P.body('Connector type'),
			},
			description: 'Add an Exchange connector template',
		},
		removeConnectorTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveExConnectorTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove an Exchange connector template',
		},
		listConnectionFilters: {
			method: 'GET',
			endpoint: '/api/ListConnectionFilter',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List connection filters for a tenant',
		},
		addConnectionFilter: {
			method: 'POST',
			endpoint: '/api/AddConnectionFilter',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodySelected,
			params: {
				PowerShellCommand: P.body('PowerShell command'),
				TemplateList: P.bodyJson('Template JSON'),
			},
			description: 'Add a connection filter to a tenant',
		},
		listConnectionFilterTemplates: {
			method: 'GET',
			endpoint: '/api/ListConnectionFilterTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.none,
			params: {
				id: P.qs('Template ID'),
			},
			description: 'List connection filter templates',
		},
		addConnectionFilterTemplate: {
			method: 'POST',
			endpoint: '/api/AddConnectionFilterTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				name: P.body('Template name', true),
				PowerShellCommand: P.body('PowerShell command'),
			},
			description: 'Add a connection filter template',
		},
		removeConnectionFilterTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveConnectionfilterTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove a connection filter template',
		},
	},
};
