import type { ResourceConfig } from './types';
import { P, TENANT } from './types';

export const resourceConfig: ResourceConfig = {
	label: 'User',
	description: 'Manage Azure AD users, MFA, sign-ins, JIT admin, and user defaults',
	operations: {
		getAll: {
			method: 'GET',
			endpoint: '/api/ListGraphRequest',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				userFields: P.qs('Fields to return (comma-separated)'),
				$filter: P.qs('OData filter'),
				$select: P.qs('OData select'),
			},
			description: 'List all users via Graph (requires Endpoint=users in QS)',
		},
		listUsers: {
			method: 'GET',
			endpoint: '/api/ListUsers',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				graphFilter: P.qs('Graph filter'),
				IncludeLogonDetails: P.qsBool('Include logon details'),
				UserID: P.qs('User ID'),
			},
			description: 'List users for a tenant',
		},
		add: {
			method: 'POST',
			endpoint: '/api/AddUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				givenName: P.body('First name', true),
				surname: P.body('Last name', true),
				PrimDomain: P.body('Domain', true),
				DisplayName: P.body('Display name'),
			},
			description: 'Add a new user to a tenant',
		},
		edit: {
			method: 'PATCH',
			endpoint: '/api/EditUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				id: P.body('User ID', true),
			},
			description: 'Edit a user',
		},
		patchUser: {
			method: 'PATCH',
			endpoint: '/api/PatchUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				id: P.body('User ID', true),
			},
			description: 'Patch a user via direct Graph update',
		},
		disable: {
			method: 'POST',
			endpoint: '/api/ExecDisableUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
			},
			defaults: { body: { Enable: 'false' } },
			description: 'Disable a user account',
		},
		enable: {
			method: 'POST',
			endpoint: '/api/ExecDisableUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
			},
			defaults: { body: { Enable: 'true' } },
			description: 'Enable a user account',
		},
		resetPassword: {
			method: 'POST',
			endpoint: '/api/ExecResetPass',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
				MustChange: P.bodyBool('Must change on login'),
			},
			description: 'Reset a user password',
		},
		remove: {
			method: 'POST',
			endpoint: '/api/RemoveUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
			},
			description: 'Remove a user from a tenant',
		},
		resetMfa: {
			method: 'POST',
			endpoint: '/api/ExecResetMFA',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
			},
			description: 'Reset MFA for a user',
		},
		sendMfaPush: {
			method: 'POST',
			endpoint: '/api/ExecSendPush',
			isWrite: true,
			isList: false,
			tenant: TENANT.bodyPascal,
			params: {
				UserEmail: P.body('User email', true),
			},
			description: 'Send an MFA push notification to a user',
		},
		setPerUserMfa: {
			method: 'POST',
			endpoint: '/api/ExecPerUserMFA',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userId: P.body('User ID', true),
				State: P.bodyEnum('MFA state', ['Enforced', 'Enabled', 'Disabled'], true),
			},
			description: 'Set per-user MFA state',
		},
		createTap: {
			method: 'POST',
			endpoint: '/api/ExecCreateTAP',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
			},
			description: 'Create a Temporary Access Pass for a user',
		},
		clearImmutableId: {
			method: 'POST',
			endpoint: '/api/ExecClrImmId',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
			},
			description: 'Clear the immutable ID for a user',
		},
		revokeSessions: {
			method: 'POST',
			endpoint: '/api/ExecRevokeSessions',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				ID: P.body('User ID', true),
			},
			description: 'Revoke all sessions for a user',
		},
		offboard: {
			method: 'POST',
			endpoint: '/api/ExecOffboardUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				user: P.bodyJson('Users JSON array', true),
			},
			description: 'Offboard a user',
		},
		listInactiveAccounts: {
			method: 'GET',
			endpoint: '/api/ListInactiveAccounts',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				InactiveDays: P.qsNum('Days inactive'),
			},
			description: 'List inactive user accounts',
		},
		listSignIns: {
			method: 'GET',
			endpoint: '/api/ListSignIns',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				Days: P.qsNum('Days to look back'),
				failedLogonsOnly: P.qsBool('Failed only'),
			},
			description: 'List user sign-in events',
		},
		listMfaUsers: {
			method: 'GET',
			endpoint: '/api/ListMFAUsers',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List MFA status for all users',
		},
		dismissRiskyUser: {
			method: 'POST',
			endpoint: '/api/ExecDismissRiskyUser',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userId: P.body('User ID', true),
			},
			description: 'Dismiss a risky user alert',
		},
		listJitAdmin: {
			method: 'GET',
			endpoint: '/api/ListJITAdmin',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List JIT admin assignments',
		},
		execJitAdmin: {
			method: 'POST',
			endpoint: '/api/ExecJITAdmin',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				userAction: P.body('User action', true),
				AdminRoles: P.body('Admin roles', true),
				StartDate: P.body('Start date', true),
				EndDate: P.body('End date', true),
				ExpireAction: P.body('Expire action', true),
				UseTAP: P.bodyBool('Use TAP', true),
			},
			description: 'Execute a JIT admin action',
		},
		addGuest: {
			method: 'POST',
			endpoint: '/api/AddGuest',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				displayName: P.body('Display name', true),
				mail: P.body('Email', true),
			},
			description: 'Add a guest user to a tenant',
		},
		addUserBulk: {
			method: 'POST',
			endpoint: '/api/AddUserBulk',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				BulkUser: P.bodyJson('Bulk user JSON', true),
			},
			description: 'Add multiple users in bulk',
		},
		execBecCheck: {
			method: 'GET',
			endpoint: '/api/ExecBECCheck',
			isWrite: false,
			isList: false,
			tenant: TENANT.qs,
			params: {
				GUID: P.qs('GUID'),
				userid: P.qs('User ID'),
				userName: P.qs('Username'),
			},
			description: 'Run a Business Email Compromise check',
		},
		execBecRemediate: {
			method: 'POST',
			endpoint: '/api/ExecBECRemediate',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {},
			description: 'Remediate a Business Email Compromise',
		},
		triggerBulkLicense: {
			method: 'GET',
			endpoint: '/api/ExecBulkLicense',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {},
			description: 'Trigger bulk license assignment',
		},
		setPasswordNeverExpires: {
			method: 'POST',
			endpoint: '/api/ExecPasswordNeverExpires',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {},
			description: 'Set password to never expire for a user',
		},
		reprocessLicenses: {
			method: 'POST',
			endpoint: '/api/ExecReprocessUserLicenses',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {},
			description: 'Reprocess license assignments for a user',
		},
		setUserPhoto: {
			method: 'POST',
			endpoint: '/api/ExecSetUserPhoto',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				action: P.body('Photo action', true),
			},
			description: 'Set or remove a user photo',
		},
		listUserCaPolicies: {
			method: 'GET',
			endpoint: '/api/ListUserConditionalAccessPolicies',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				UserID: P.qs('User ID'),
			},
			description: 'List conditional access policies applied to a user',
		},
		listUserCounts: {
			method: 'GET',
			endpoint: '/api/ListUserCounts',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List user count statistics',
		},
		listUserDevices: {
			method: 'GET',
			endpoint: '/api/ListUserDevices',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				UserID: P.qs('User ID'),
			},
			description: 'List devices associated with a user',
		},
		listUserGroups: {
			method: 'GET',
			endpoint: '/api/ListUserGroups',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				userId: P.qs('User ID'),
			},
			description: 'List groups a user belongs to',
		},
		listUserMailboxDetails: {
			method: 'GET',
			endpoint: '/api/ListUserMailboxDetails',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				UserID: P.qs('User ID'),
				userMail: P.qs('User email'),
			},
			description: 'List mailbox details for a user',
		},
		listUserMailboxRules: {
			method: 'GET',
			endpoint: '/api/ListUserMailboxRules',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				UserID: P.qs('User ID'),
				userEmail: P.qs('User email'),
			},
			description: 'List mailbox rules for a user',
		},
		listUserSettings: {
			method: 'GET',
			endpoint: '/api/ListUserSettings',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'List user settings',
		},
		listPerUserMfa: {
			method: 'GET',
			endpoint: '/api/ListPerUserMFA',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				userId: P.qs('User ID'),
				allUsers: P.qsBool('Include all users'),
			},
			description: 'List per-user MFA status',
		},
		listTrustedBlockedSenders: {
			method: 'GET',
			endpoint: '/api/ListUserTrustedBlockedSenders',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				UserID: P.qs('User ID'),
				userPrincipalName: P.qs('UPN'),
			},
			description: 'List trusted and blocked senders for a user',
		},
		removeTrustedBlockedSender: {
			method: 'POST',
			endpoint: '/api/RemoveTrustedBlockedSender',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				typeProperty: P.body('Type', true),
				value: P.body('Value', true),
				userPrincipalName: P.body('User UPN', true),
			},
			description: 'Remove a trusted or blocked sender entry',
		},
		addJitTemplate: {
			method: 'POST',
			endpoint: '/api/AddJITAdminTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				templateName: P.body('Template name', true),
			},
			description: 'Add a JIT admin template',
		},
		editJitTemplate: {
			method: 'POST',
			endpoint: '/api/EditJITAdminTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				templateName: P.body('Template name', true),
				GUID: P.body('Template GUID', true),
			},
			description: 'Edit a JIT admin template',
		},
		removeJitTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveJITAdminTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove a JIT admin template',
		},
		listJitTemplates: {
			method: 'POST',
			endpoint: '/api/ListJITAdminTemplates',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				GUID: P.qs('Template GUID'),
				includeAllTenants: P.qsBool('Include all tenants'),
			},
			description: 'List JIT admin templates',
		},
		editUserAliases: {
			method: 'POST',
			endpoint: '/api/EditUserAliases',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {
				id: P.body('User ID', true),
			},
			description: 'Edit email aliases for a user',
		},
		listUserPhoto: {
			method: 'GET',
			endpoint: '/api/ListUserPhoto',
			isWrite: false,
			isList: false,
			tenant: TENANT.qs,
			params: {
				UserID: P.qs('User ID'),
			},
			description: 'Get a user photo',
		},
		listUserSigninLogs: {
			method: 'GET',
			endpoint: '/api/ListUserSigninLogs',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				top: P.qsNum('Max results'),
				UserID: P.qs('User ID'),
			},
			description: 'List sign-in logs for a user',
		},
		addUserDefaults: {
			method: 'POST',
			endpoint: '/api/AddUserDefaults',
			isWrite: true,
			isList: false,
			tenant: TENANT.body,
			params: {},
			description: 'Add user default settings',
		},
		removeUserDefaultTemplate: {
			method: 'POST',
			endpoint: '/api/RemoveUserDefaultTemplate',
			isWrite: true,
			isList: false,
			tenant: TENANT.none,
			params: {
				ID: P.body('Template ID', true),
			},
			description: 'Remove a user default template',
		},
		listNewUserDefaults: {
			method: 'POST',
			endpoint: '/api/ListNewUserDefaults',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {
				ID: P.qs('Defaults ID'),
				includeAllTenants: P.qsBool('Include all tenants'),
			},
			description: 'List new user default templates',
		},
		listUsersAndGroups: {
			method: 'GET',
			endpoint: '/api/ListUsersAndGroups',
			isWrite: false,
			isList: true,
			tenant: TENANT.qs,
			params: {},
			description: 'Get a combined directory snapshot of all users and groups for a tenant',
		},
	},
};
